apiVersion: "pipelinesascode.tekton.dev/v1alpha1"
kind: Repository
metadata:
  name: uoi3fgkq2-java-quarkus-gitops-repository
spec:
  url: https://github.com/rhtap-rhdh-qe/uoi3fgkq2-java-quarkus-gitops